import { createContext, useContext } from "react";

/** The themes. A value is four things at once: the `data-theme` attribute, the key stored in
 *  localStorage, the name of a block in styles.css, and a key in index.html's bootstrap map.
 *  Every value in those blocks is generated by `frontend/tools/themes.py`, which enforces the
 *  contrast floors; adding a theme means adding it there, re-running it, and adding a row here. */
export type Theme =
  | "bronze"
  | "fintech"
  | "monochrome"
  | "teal-navy"
  | "earthy"
  | "security"
  | "citrus";

export const DEFAULT_THEME: Theme = "bronze";

/** `swatch` is ground, accent, second accent -- what tells the themes apart at a glance. `desc`
 *  is there because a name alone does not say what a theme looks like. */
export const THEMES: { value: Theme; label: string; desc: string; swatch: [string, string, string] }[] = [
  { value: "bronze", label: "Bronze", desc: "Charcoal with a bronze accent", swatch: ["#0d0f12", "#b98a44", "#d3a45a"] },
  { value: "fintech", label: "Fintech Classic", desc: "Deep navy with a teal accent", swatch: ["#0a2540", "#00d4b2", "#7dd3fc"] },
  { value: "monochrome", label: "Monochrome", desc: "Near-black, one amber pop", swatch: ["#111827", "#f59e0b", "#e5e7eb"] },
  { value: "teal-navy", label: "Teal & Navy", desc: "Slate navy with orange and teal", swatch: ["#1e293b", "#f68a3f", "#6bbab4"] },
  { value: "earthy", label: "Earthy Green", desc: "Warm stone with amber and emerald", swatch: ["#292524", "#df9337", "#5eb895"] },
  { value: "security", label: "Security Slate", desc: "Lifted slate with emerald", swatch: ["#374151", "#7ed4b9", "#ccd0d6"] },
  { value: "citrus", label: "Marketing Citrus", desc: "Near-black with citrus yellow", swatch: ["#1c1917", "#facc15", "#eb7839"] },
];

export function isTheme(value: unknown): value is Theme {
  return THEMES.some((t) => t.value === value);
}

/** Read a stored value as a theme. Two generations of names have been retired here: the teal
 *  `"light"`/`"dark"` pair, and the palettes tried and scrapped on 2026-09-20. Anything
 *  unrecognised lands on the default rather than leaving the app unpainted. */
export function migrateTheme(stored: string | null): Theme {
  return isTheme(stored) ? stored : DEFAULT_THEME;
}

export const ThemeContext = createContext<{ theme: Theme; setTheme: (t: Theme) => void }>({
  theme: DEFAULT_THEME,
  setTheme: () => {},
});
export const useTheme = () => useContext(ThemeContext);
